
package cn.sky.test.webservice.client.ecard.dto;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ClientProtocolException", targetNamespace = "http://service.ws.ecard.amway.com/")
public class ClientProtocolException_Exception
    extends java.lang.Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = 6482784948130237956L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ClientProtocolException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ClientProtocolException_Exception(String message, ClientProtocolException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ClientProtocolException_Exception(String message, ClientProtocolException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: cn.sky.test.webservice.client.ecard.dto.ClientProtocolException
     */
    public ClientProtocolException getFaultInfo() {
        return faultInfo;
    }

}
