
package cn.sky.test.webservice.client.ecard.dto;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ECardService", targetNamespace = "http://service.ws.ecard.amway.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ECardService {


    /**
     * 
     * @param simpleList
     * @return
     *     returns cn.sky.test.webservice.client.ecard.dto.ResultDTO
     */
    @WebMethod
    @WebResult(name = "ResultDTO", targetNamespace = "")
    @RequestWrapper(localName = "meetingTicketDelete", targetNamespace = "http://service.ws.ecard.amway.com/", className = "cn.sky.test.webservice.client.ecard.dto.MeetingTicketDelete")
    @ResponseWrapper(localName = "meetingTicketDeleteResponse", targetNamespace = "http://service.ws.ecard.amway.com/", className = "cn.sky.test.webservice.client.ecard.dto.MeetingTicketDeleteResponse")
    @Action(input = "http://service.ws.ecard.amway.com/ECardService/meetingTicketDeleteRequest", output = "http://service.ws.ecard.amway.com/ECardService/meetingTicketDeleteResponse")
    public ResultDTO meetingTicketDelete(
        @WebParam(name = "simpleList", targetNamespace = "http://impl.ws.com")
        List<ActivityTicketSimpleDTO> simpleList);

    /**
     * 
     * @param ticketNoDTO
     * @return
     *     returns cn.sky.test.webservice.client.ecard.dto.ResultDTO
     */
    @WebMethod
    @WebResult(name = "ResultDTO", targetNamespace = "")
    @RequestWrapper(localName = "updateWeChatMeetingFlag", targetNamespace = "http://service.ws.ecard.amway.com/", className = "cn.sky.test.webservice.client.ecard.dto.UpdateWeChatMeetingFlag")
    @ResponseWrapper(localName = "updateWeChatMeetingFlagResponse", targetNamespace = "http://service.ws.ecard.amway.com/", className = "cn.sky.test.webservice.client.ecard.dto.UpdateWeChatMeetingFlagResponse")
    @Action(input = "http://service.ws.ecard.amway.com/ECardService/updateWeChatMeetingFlagRequest", output = "http://service.ws.ecard.amway.com/ECardService/updateWeChatMeetingFlagResponse")
    public ResultDTO updateWeChatMeetingFlag(
        @WebParam(name = "ticketNoDTO", targetNamespace = "http://impl.ws.com")
        String ticketNoDTO);

    /**
     * 
     * @param list
     * @return
     *     returns cn.sky.test.webservice.client.ecard.dto.ResultDTO
     */
    @WebMethod
    @WebResult(name = "ResultDTO", targetNamespace = "")
    @RequestWrapper(localName = "meetingTicketUpdated", targetNamespace = "http://service.ws.ecard.amway.com/", className = "cn.sky.test.webservice.client.ecard.dto.MeetingTicketUpdated")
    @ResponseWrapper(localName = "meetingTicketUpdatedResponse", targetNamespace = "http://service.ws.ecard.amway.com/", className = "cn.sky.test.webservice.client.ecard.dto.MeetingTicketUpdatedResponse")
    @Action(input = "http://service.ws.ecard.amway.com/ECardService/meetingTicketUpdatedRequest", output = "http://service.ws.ecard.amway.com/ECardService/meetingTicketUpdatedResponse")
    public ResultDTO meetingTicketUpdated(
        @WebParam(name = "list", targetNamespace = "http://impl.ws.com")
        List<ActivityTicketDTO> list);

    /**
     * 
     * @param activityMeetingDTOs
     * @return
     *     returns cn.sky.test.webservice.client.ecard.dto.ResultDTO
     */
    @WebMethod
    @WebResult(name = "ResultDTO", targetNamespace = "")
    @RequestWrapper(localName = "meetingCreatedOrUpdated", targetNamespace = "http://service.ws.ecard.amway.com/", className = "cn.sky.test.webservice.client.ecard.dto.MeetingCreatedOrUpdated")
    @ResponseWrapper(localName = "meetingCreatedOrUpdatedResponse", targetNamespace = "http://service.ws.ecard.amway.com/", className = "cn.sky.test.webservice.client.ecard.dto.MeetingCreatedOrUpdatedResponse")
    @Action(input = "http://service.ws.ecard.amway.com/ECardService/meetingCreatedOrUpdatedRequest", output = "http://service.ws.ecard.amway.com/ECardService/meetingCreatedOrUpdatedResponse")
    public ResultDTO meetingCreatedOrUpdated(
        @WebParam(name = "ActivityMeetingDTOs", targetNamespace = "http://impl.ws.com")
        List<ActivityMeetingDTO> activityMeetingDTOs);

    /**
     * 
     * @param list
     * @return
     *     returns cn.sky.test.webservice.client.ecard.dto.ResultDTO
     */
    @WebMethod
    @WebResult(name = "ResultDTO", targetNamespace = "")
    @RequestWrapper(localName = "meetingTicketCreated", targetNamespace = "http://service.ws.ecard.amway.com/", className = "cn.sky.test.webservice.client.ecard.dto.MeetingTicketCreated")
    @ResponseWrapper(localName = "meetingTicketCreatedResponse", targetNamespace = "http://service.ws.ecard.amway.com/", className = "cn.sky.test.webservice.client.ecard.dto.MeetingTicketCreatedResponse")
    @Action(input = "http://service.ws.ecard.amway.com/ECardService/meetingTicketCreatedRequest", output = "http://service.ws.ecard.amway.com/ECardService/meetingTicketCreatedResponse")
    public ResultDTO meetingTicketCreated(
        @WebParam(name = "list", targetNamespace = "http://impl.ws.com")
        List<ActivityTicketDTO> list);

    /**
     * 
     * @param weChatOrderCloserDTOs
     * @return
     *     returns cn.sky.test.webservice.client.ecard.dto.WechatOrderQueryResultDTO
     * @throws ClientProtocolException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(name = "WechatOrderQueryResultDTO", targetNamespace = "")
    @RequestWrapper(localName = "wechatOrderPublicCloser", targetNamespace = "http://service.ws.ecard.amway.com/", className = "cn.sky.test.webservice.client.ecard.dto.WechatOrderPublicCloser")
    @ResponseWrapper(localName = "wechatOrderPublicCloserResponse", targetNamespace = "http://service.ws.ecard.amway.com/", className = "cn.sky.test.webservice.client.ecard.dto.WechatOrderPublicCloserResponse")
    @Action(input = "http://service.ws.ecard.amway.com/ECardService/wechatOrderPublicCloserRequest", output = "http://service.ws.ecard.amway.com/ECardService/wechatOrderPublicCloserResponse", fault = {
        @FaultAction(className = ClientProtocolException_Exception.class, value = "http://service.ws.ecard.amway.com/ECardService/wechatOrderPublicCloser/Fault/ClientProtocolException"),
        @FaultAction(className = IOException_Exception.class, value = "http://service.ws.ecard.amway.com/ECardService/wechatOrderPublicCloser/Fault/IOException")
    })
    public WechatOrderQueryResultDTO wechatOrderPublicCloser(
        @WebParam(name = "weChatOrderCloserDTOs", targetNamespace = "http://impl.ws.com")
        WeChatOrderCloserDTOs weChatOrderCloserDTOs)
        throws ClientProtocolException_Exception, IOException_Exception
    ;

    /**
     * 
     * @param weChatOrderQueryDTOs
     * @return
     *     returns cn.sky.test.webservice.client.ecard.dto.WechatOrderQueryResultDTO
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "WechatOrderQueryResultDTO", targetNamespace = "")
    @RequestWrapper(localName = "wechatOrderPublicQuery", targetNamespace = "http://service.ws.ecard.amway.com/", className = "cn.sky.test.webservice.client.ecard.dto.WechatOrderPublicQuery")
    @ResponseWrapper(localName = "wechatOrderPublicQueryResponse", targetNamespace = "http://service.ws.ecard.amway.com/", className = "cn.sky.test.webservice.client.ecard.dto.WechatOrderPublicQueryResponse")
    @Action(input = "http://service.ws.ecard.amway.com/ECardService/wechatOrderPublicQueryRequest", output = "http://service.ws.ecard.amway.com/ECardService/wechatOrderPublicQueryResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://service.ws.ecard.amway.com/ECardService/wechatOrderPublicQuery/Fault/Exception")
    })
    public WechatOrderQueryResultDTO wechatOrderPublicQuery(
        @WebParam(name = "weChatOrderQueryDTOs", targetNamespace = "http://impl.ws.com")
        WeChatOrderQueryDTOs weChatOrderQueryDTOs)
        throws Exception_Exception
    ;

    /**
     * 
     * @param args
     * @return
     *     returns cn.sky.test.webservice.client.ecard.dto.AuthVerificationResultDTO
     */
    @WebMethod
    @WebResult(name = "AuthVerificationResultDTO", targetNamespace = "")
    @RequestWrapper(localName = "verifyAdaCardAuthorization", targetNamespace = "http://service.ws.ecard.amway.com/", className = "cn.sky.test.webservice.client.ecard.dto.VerifyAdaCardAuthorization")
    @ResponseWrapper(localName = "verifyAdaCardAuthorizationResponse", targetNamespace = "http://service.ws.ecard.amway.com/", className = "cn.sky.test.webservice.client.ecard.dto.VerifyAdaCardAuthorizationResponse")
    @Action(input = "http://service.ws.ecard.amway.com/ECardService/verifyAdaCardAuthorizationRequest", output = "http://service.ws.ecard.amway.com/ECardService/verifyAdaCardAuthorizationResponse")
    public AuthVerificationResultDTO verifyAdaCardAuthorization(
        @WebParam(name = "args", targetNamespace = "http://impl.ws.com")
        QRCodeDTO args);

    /**
     * 
     * @param weChatCardDTO
     * @return
     *     returns cn.sky.test.webservice.client.ecard.dto.ResultDTO
     */
    @WebMethod
    @WebResult(name = "ResultDTO", targetNamespace = "")
    @RequestWrapper(localName = "updateWeChatCard", targetNamespace = "http://service.ws.ecard.amway.com/", className = "cn.sky.test.webservice.client.ecard.dto.UpdateWeChatCard")
    @ResponseWrapper(localName = "updateWeChatCardResponse", targetNamespace = "http://service.ws.ecard.amway.com/", className = "cn.sky.test.webservice.client.ecard.dto.UpdateWeChatCardResponse")
    @Action(input = "http://service.ws.ecard.amway.com/ECardService/updateWeChatCardRequest", output = "http://service.ws.ecard.amway.com/ECardService/updateWeChatCardResponse")
    public ResultDTO updateWeChatCard(
        @WebParam(name = "weChatCardDTO", targetNamespace = "http://impl.ws.com")
        WeChatDTO weChatCardDTO);

    /**
     * 
     * @param weChatCardDTO
     * @return
     *     returns cn.sky.test.webservice.client.ecard.dto.ResultDTO
     */
    @WebMethod
    @WebResult(name = "ResultDTO", targetNamespace = "")
    @RequestWrapper(localName = "createWeChatCard", targetNamespace = "http://service.ws.ecard.amway.com/", className = "cn.sky.test.webservice.client.ecard.dto.CreateWeChatCard")
    @ResponseWrapper(localName = "createWeChatCardResponse", targetNamespace = "http://service.ws.ecard.amway.com/", className = "cn.sky.test.webservice.client.ecard.dto.CreateWeChatCardResponse")
    @Action(input = "http://service.ws.ecard.amway.com/ECardService/createWeChatCardRequest", output = "http://service.ws.ecard.amway.com/ECardService/createWeChatCardResponse")
    public ResultDTO createWeChatCard(
        @WebParam(name = "weChatCardDTO", targetNamespace = "http://impl.ws.com")
        WeChatDTO weChatCardDTO);

}
