
package cn.sky.test.webservice.client.hub.dto;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Hub", targetNamespace = "http://impl.webservice.test.sky.cn/", wsdlLocation = "http://a.w:9090/ws/Hub?wsdl")
public class Hub
    extends Service
{

    private final static URL HUB_WSDL_LOCATION;
    private final static WebServiceException HUB_EXCEPTION;
    private final static QName HUB_QNAME = new QName("http://impl.webservice.test.sky.cn/", "Hub");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://a.w:9090/ws/Hub?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HUB_WSDL_LOCATION = url;
        HUB_EXCEPTION = e;
    }

    public Hub() {
        super(__getWsdlLocation(), HUB_QNAME);
    }

    public Hub(WebServiceFeature... features) {
        super(__getWsdlLocation(), HUB_QNAME, features);
    }

    public Hub(URL wsdlLocation) {
        super(wsdlLocation, HUB_QNAME);
    }

    public Hub(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HUB_QNAME, features);
    }

    public Hub(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Hub(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HubService
     */
    @WebEndpoint(name = "HubServiceImplPort")
    public HubService getHubServiceImplPort() {
        return super.getPort(new QName("http://impl.webservice.test.sky.cn/", "HubServiceImplPort"), HubService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HubService
     */
    @WebEndpoint(name = "HubServiceImplPort")
    public HubService getHubServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.webservice.test.sky.cn/", "HubServiceImplPort"), HubService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HUB_EXCEPTION!= null) {
            throw HUB_EXCEPTION;
        }
        return HUB_WSDL_LOCATION;
    }

}
