
package cn.sky.test.webservice.client.hub.dto;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HubService", targetNamespace = "http://webservice.test.sky.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HubService {


    /**
     * 
     * @param msg
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "msg", targetNamespace = "http://webservice.test.sky.cn/", className = "cn.sky.test.webservice.client.hub.dto.Msg")
    @ResponseWrapper(localName = "msgResponse", targetNamespace = "http://webservice.test.sky.cn/", className = "cn.sky.test.webservice.client.hub.dto.MsgResponse")
    public String msg(
        @WebParam(name = "msg", targetNamespace = "")
        String msg);

    /**
     * 
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "token", targetNamespace = "http://webservice.test.sky.cn/", className = "cn.sky.test.webservice.client.hub.dto.Token")
    @ResponseWrapper(localName = "tokenResponse", targetNamespace = "http://webservice.test.sky.cn/", className = "cn.sky.test.webservice.client.hub.dto.TokenResponse")
    public String token(
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @param adaNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Lest")
    @WebResult(name = "Lest", targetNamespace = "")
    @RequestWrapper(localName = "Lest", targetNamespace = "http://webservice.test.sky.cn/", className = "cn.sky.test.webservice.client.hub.dto.Lest")
    @ResponseWrapper(localName = "LestResponse", targetNamespace = "http://webservice.test.sky.cn/", className = "cn.sky.test.webservice.client.hub.dto.LestResponse")
    public String lest(
        @WebParam(name = "AdaNo", targetNamespace = "")
        String adaNo);

}
